### ISSUE TITLE
No figure results

### ISSUE THREAD

**Issue by wyzhangMPI** [roblanf/minion_qc#28] opened 2018-02-18 11:07 UTC
Hi,
   I am trying to use minion_qc for the quality of check of base-calling data from Albacore. However, I didnot get figure results from this (only summary.yaml).
$ Rscript /home/wyzhang/opt/biosoftware/ONT_Analysis_Tools/minion_qc/MinionQC.R -i ./sequencing_summary.txt -o my_example_output

Attaching package: ‘scales’

The following object is masked from ‘package:readr’:

    col_factor

The following object is masked from ‘package:viridis’:

    viridis_pal

INFO [2018-02-18 12:03:08] Loading input file: ./sequencing_summary.txt
INFO [2018-02-18 12:03:09] .: creating output directory:my_example_output
INFO [2018-02-18 12:03:09] .: summarising input file for flowcell
INFO [2018-02-18 12:03:09] .: plotting length histogram
Error in .External2(C_X11, paste0("png::", filename), g$width, g$height,  :
  unable to start device PNG
Calls: single.flowcell -> ggsave -> dev -> <Anonymous>
Execution halted

Can you help to take a look at what is going wrong there?
Thanks!

Best,
Wenyu

**Comment by roblanf** [comment] 2018-02-19 03:29
Hi There,

There's not really enough information for me to know what's going on. But I can make a guess that it could be a file permissions issue (e.g. perhaps you don't have permission to write files to the `my_example_output` that you have specified?

My reason for this guess is that the program is quitting right when it tries to write the first plot to disk.

A couple of options:

1. Check the file permissions of the folder you are writing to. In this case it's the root directory, which might be your problem.

2. Change the output directory to somewhere you have permission to write to, e.g. (from your post): `/home/wyzhang/minionQC_output`

Let me know if either of those work.

Rob

**Comment by wyzhangMPI** [comment] 2018-02-19 11:24
Hello,
    Thanks for the reply. Actually it is not the problem for the permission of writing files (the output dir is in my own dir).
Based on the error info, the problem came from "unable to start device PNG", however, checking with "> capabilities()" showed:
> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua
       TRUE        TRUE        TRUE       FALSE       FALSE       FALSE
   http/ftp     sockets      libxml        fifo      cledit       iconv
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE
        NLS     profmem       cairo         ICU long.double     libcurl
       TRUE       FALSE        TRUE       FALSE        TRUE        TRUE

It seems the "png" function is already turned on.

I also tried to run on my local computer (windows7-based) with R-studio, by modifying the input file name and output dir name in "MinionQC.R" script. It seems every thing is fine there. So I thought it might be the R version problem for our server, but not sure.

**Comment by roblanf** [comment] 2018-02-19 18:43
Ah, OK. Next best guess is that it's a version problem with R or the packages. If you can update them all to the latest versions, that might help. If not, I'm a little lost I'm afraid.

**Comment by roblanf** [comment] 2018-02-19 18:49
A few potential solutions here: 

https://stackoverflow.com/questions/24999983/r-unable-to-start-device-png-capabilities-has-true-for-png

I'd be interested to know if any of these work. Particularly using the `bitmap()` function or the `png("abc", type="cairo")` option, since I could quite easily alter all the plots to build this way if that fixes the issue.

If you were willing to try a couple of these on the first plot, I'd be interested to know the outcome. Of course, I'd do it here but so far I'm not able to reproduce the error you get.

**Comment by wyzhangMPI** [comment] 2018-02-19 18:56
Thanks for further information.
On my current R, we can run "png("abc", type="cairo")" successfully, and 
this should be a possible solution.
However, I check in your R script MinionQC.R, the png files are 
generated via "ggsave(filename = file.path(output.dir, 
"length_histogram.png"), width = 960/75, height = 960/75, plot = p1)."
How could I change in this way?


------ Original Message ------

**Comment by wyzhangMPI** [comment] 2018-02-19 19:00
Hi,
     I added "options(bitmapType='cairo')" in your R script, and now it 
works.
     Thank you so much!


------ Original Message ------

**Comment by roblanf** [comment] 2018-02-19 20:26
Fantastic! Thanks for trying this out. Much appreciated. I'll leave this issue open until I've had time to add this to the script and run all the tests.

**Comment by roblanf** [comment] 2018-05-30 01:10
hi @wyzhangMPI,

I have published a branch that I hope might fix this problem (with apologies for the long delay...).

If you are able to, could you try:

1. Running the script from here, just to check that you still get the error (sorry, because of my system I can't replicate it): https://github.com/roblanf/minion_qc/blob/master/MinIONQC.R

2. Running the script from here, to see if this fixes the error: https://github.com/roblanf/minion_qc/blob/feature/detect_png/MinIONQC.R

All it does is try to make a png, and if it can't, it uses the `options(bitmapType='cairo')` approach.

Cheers,

Rob

**Comment by roblanf** [comment] 2020-06-04 00:48
Closing this issue as we now have options for 'png', 'pdf', 'ps', 'jpeg', 'tiff', 'bmp' here: https://github.com/roblanf/minion_qc/commit/dfb88d0c058a3f16e173bdd91531ffb34e2aef62

**Closed by roblanf** 2020-06-04 00:48 UTC
